services:
  patient-service-db:
    container_name: patient-service-db
    image: postgres:latest
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    networks:
      - internal

  auth-service:
    container_name: auth-service
    image: auth-service:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - JWT_SECRET=hRE11I9k6NXaZy9lD8ClH/7O66KO92QwhGs8jF4sgA77rqUHk4cZbyvrtlCOFawc

    networks:
      - internal

  auth-service-db:
    container_name: auth-service-db
    image: postgres:latest
    ports:
      - "5001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    networks:
      - internal

  billing-service:
    container_name: billing-service
    image: billing-service:latest
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

  patient-service:
    container_name: patient-service
    image: patient-service:latest
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - billing-service
      - patient-service-db
      - kafka
    networks:
      - internal

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
    networks:
      - internal

  analytics-service:
    container_name: analytics-service
    image: analytics-service:latest
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - internal

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - AUTH_SERVICE_URL=http://auth-service:4005
    ports:
      - "4004:4004"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data: